import Constants from '../constants';
const ProductData = [
  {
    id:1,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '10',
    image: Constants.images.PRODUCT_1,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:2,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '4',
    image: Constants.images.PRODUCT_2,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:3,
    name: 'Adidas Shoes',
    brand: 'AdidS',
    size: '10',
    image: Constants.images.PRODUCT_3,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:4,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '14',
    image: Constants.images.PRODUCT_4,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:5,
    name: 'Adidas',
    brand: 'Nike',
    size: '6',
    image: Constants.images.PRODUCT_5,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:6,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '6',
    image: Constants.images.PRODUCT_6,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:7,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '7',
    image: Constants.images.PRODUCT_7,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:8,
    name: 'Adidas Shoes',
    brand: 'Adidas',
    size: '8',
    image: Constants.images.PRODUCT_8,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:9,
    name: 'Adidas Shoes',
    brand: 'Nike',
    size: '9',
    image: Constants.images.PRODUCT_9,
    price: '3000',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:10,
    name: 'Nike Shoes',
    brand: 'Nike',
    size: '4',
    image: Constants.images.PRODUCT_10,
    price: '2600',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:11,
    name: 'Puma Shoes',
    brand: 'Puma',
    size: '8',
    image: Constants.images.PRODUCT_11,
    price: '2900',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:12,
    name: 'Puma Shoes',
    brand: 'Puma',
    size: '3',
    image: Constants.images.PRODUCT_12,
    price: '2900',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:13,
    name: 'Puma sliper',
    brand: 'Puma',
    size: '3',
    image: Constants.images.PRODUCT_13,
    price: '290',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:14,
    name: 'Puma sliper',
    brand: 'Puma',
    size: '4',
    image: Constants.images.PRODUCT_14,
    price: '390',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:15,
    name: 'Puma sliper',
    brand: 'Puma',
    size: '3',
    image: Constants.images.PRODUCT_15,
    price: '490',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  {
    id:16,
    name: 'Puma sliper',
    brand: 'Puma',
    size: '5',
    image: Constants.images.PRODUCT_16,
    price: '190',
    description: '"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam',
  },
  ];
export default{
    ProductData
}